### ISSUE TITLE
Error When saving firstname and lastname of user profile

### ISSUE THREAD

**Issue by m-henderson** [mentorient/mentorient#88]
![image](https://user-images.githubusercontent.com/16070192/35365092-424949bc-0138-11e8-96fd-78caffff4617.png)

I will add some more info about this when i run in dev environment

**Comment by drazenp** [comment]
The issue is probably an old user without claim added in the db. Right now on update first name try to replace existing claim and fail if claim doesn't exists.

Here is the sql query which should fix the issue (hopefully :) ). I'm not sure if this is the best option, or this should be part of the migration?

`insert into AspNetUserClaims (ClaimType, ClaimValue, UserId)
select 'urn:mentorient:firstname', 'Enter your name', u.Id
from AspNetUsers u
left join AspNetUserClaims c on c.UserId=u.Id
where c.UserId is null`

I will create and PR to fix this in the code will fallback, but if this is necessarily since First Name is required?

**Comment by drazenp** [comment]
I have created PR, but I'm not sure if it's really needed.
There is and small fallback to show username in the salutation if first name doesn't exits.

**Comment by m-henderson** [comment]
@drazenp what was causing the issue?

**Comment by m-henderson** [comment]
I believe this is fixed; i amm closing.
